### PR TITLE
feat: add HK RunningSpeed to permissions

### PR DESCRIPTION
**Pull request by walterholohan**
## Description

We use react-native-health to ask users to accept HK permissions of metrics that we use in our Apple Watch app. In WatchOS9 'RunningSpeed' was released which will return the pace of the user while running outside. This PR exposes the new metric to the Permissions module of this library

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by walterholohan** [comment]
@GGGava can you take a look at this PR please?

**Comment by vojto** [comment]
+1

**Review by GGGava — APPROVED** [review]

**Comment by GGGava** [comment]
Hey @walterholohan thank you very much for your contribution and I'm really sorry for the time I took to review your PR. Could you fix the conflicts in this PR so I can merge it? thanks :D

**Comment by walterholohan** [comment]
@GGGava conflicts now resolved

**Comment by walterholohan** [comment]
> +1
> 
> if this repo is not maintained, perhaps worth considering https://github.com/kingstinct/react-native-healthkit

@vojto thank you for this, and something we will look into. As currently, react-native-health does not support saving a full workout to healthKit but I can see that this library does or seems to do with `saveWorkoutSample`

**Pull request merged**
