### PR TITLE
Add getWorkoutRouteSamples to library

### PR DESCRIPTION
**Pull request by nguyening20**
## Description

Added getWorkoutRouteSamples to the library.

Fixes https://github.com/agencyenterprise/react-native-health/issues/208

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by walterholohan** [comment]
@macelai would you be able to review this PR please?

**Comment by walterholohan** [comment]
I've tested this PR on my project and it works

**Comment by macelai** [comment]
@GGGava any chance to take a look at this?

**Comment by mgfuller333** [comment]
Yeah hopefully we can get this merged

**Review by GGGava — APPROVED** [review]

**Comment by walterholohan** [comment]
Great stuff, do we know who has write access to merge and create a new release?

**Comment by walterholohan** [comment]
Bumping this, the changes in this PR have been live in our production app for the last 2 weeks and we've had no issues to date 

@macelai @GGGava

**Comment by macelai** [comment]
@walterholohan just release a new version, thanks!

**Pull request merged**
