### PR TITLE
Add getFiberSamples

### LINKED ISSUE #273: Fix API inconsistency by allowing to get fiber samples
**Is your feature request related to a problem? Please describe.**
No, but there is an open question #212

**Describe the solution you'd like**
Get fiber samples the same way you can get Protein, Carbs and Fat

**Describe alternatives you've considered**
As far as I can see there is no alternative.

**Additional context**
A use can ask for fiber permission `AppleHealthKit.Constants.Permissions.Fiber`. So there is an API inconsistency

### PR DESCRIPTION
**Pull request by hstaudacher**
## Description

This PR adds support for getting `fiber` values the same way as getting e.g. `protein`. Also the `README.md` was updated and docs added for the new `fiber` support.

Fixes #273

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by LuisDanielCova** [comment]
When is this getting merged? I would like to use it for an app

**Comment by jesusamaro25** [comment]
Any update on this? I also need this.

**Comment by macelai** [comment]
did anyone try out this PR?

**Review by GGGava — APPROVED** [review]

**Comment by GGGava** [comment]
Amazing! Thank you for your contribution 😄

**Pull request merged**
